remote_theme: Drassil/git-wiki-theme@master
title: "git-wiki-skeleton"
git_branch: "master"

defaults:
 -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "git-wiki-default"
